Repository AhmedAl-Hayali/GenreGuru, pull requests merged in 2025-03, with the labels that each got.

#409 dev[vnv]: add key and scale tests
  test/test_featurizer/test_key_and_scale.py
Labels: Deliverable Item, VnV, Dev

#407 dev[vnv]: Add BPM Estimation tests
  test/test_featurizer/test_BPM.py
Labels: Deliverable Item, VnV, Dev

#414 dev[vnv]: Unit Test for Spectral Contrast
  test/test_featurizer/test_spectral_contrast.py
Labels: Deliverable Item, VnV, Dev

#412 dev[vnv]: Unit Test for Spectral Centroid
  test/test_featurizer/test_spectral_centroid.py
Labels: Deliverable Item, VnV, Dev

#411 dev[vnv]: Unit Test for Spectral Flux
  test/test_featurizer/test_spectral_flux.py
Labels: Deliverable Item, VnV, Dev

#408 dev[vnv] - Unit test for Spectral Bandwidth
  test/test_featurizer/test_spectral_bandwidth.py
Labels: Deliverable Item, VnV, Dev

#406 dev[vnv] - Unit Test for Spectral Rolloff
  test/test_featurizer/test_spectral_rolffoff.py
  test/test_featurizer/test_spectral_rolloff.py
Labels: Deliverable Item, VnV, Dev

#410 Dev[VnV]: unit tests for main featurizer, rms, dynamic range, instrumentalness, audio_splitter
  .gitignore
  src/featurizer/main_featurizer.py
  test/test_audio_features.py
  test/test_featurizer/test_audio_splitter.py
  test/test_featurizer/test_dynamic_range.py
  test/test_featurizer/test_instrumentalness.py
  test/test_featurizer/test_main_featurizer.py
  test/test_featurizer/test_rms.py
Labels: Deliverable Item, VnV

#415 docs[vnv]: Created VnV Report
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
Labels: Documentation, Deliverable Item, VnV, VnVReport
